# https://taskfile.dev/installation/

version: '3'


vars:
  # small protection from deploying to wrong account
  EXPECTED_AWS_ACCOUNT_ID: "647278206015"


dotenv: ['.env']
silent: true

tasks:
  lint:
    desc: various code and config checks
    cmds:
      - golangci-lint run --fix ./...
      - sam validate --lint
  check-aws-account:
    cmds:
      - |
        echo "Checking AWS account..."
        CURRENT_AWS_ACCOUNT=$(aws sts get-caller-identity --query Account --output text)
        if [ "$CURRENT_AWS_ACCOUNT" != "{{.EXPECTED_AWS_ACCOUNT_ID}}" ]; then
          echo "Error: Incorrect AWS account. Expected {{.EXPECTED_AWS_ACCOUNT_ID}}, but got $CURRENT_AWS_ACCOUNT."
          exit 1
        fi
  build-ui:
    dir: ui
    cmds:
      - npm run build
    sources:
      - node_modules/**/*
      - src/**/*
  build-sam:
    deps:
      - build-ui
    cmds:
      - sam build
    sources:
      - ./**/*.go
      - ui/build/**
      - template.yaml
      - samconfig.toml
  clean:
    desc: deletes all built artifacts for clean rebuild
    cmds:
      - rm -rf ui/build
      - rm -rf .aws-sam
  deploy:
    desc: rebuilds everything and deploys lambda with AWS SAM
    deps:
      - check-aws-account
      - lint
      - build-ui
      - build-sam
    cmds:
      - sam deploy
  apiserver:
    desc: runs API server. needs to be restarted after code changes.
    deps:
      - build-sam
    cmds:
      - sam local start-api --env-vars local-env-vars.json
  uiserver:
    desc: runs UI server. has live reload; needs api server running in parallel
    dir: ui
    cmds:
      - npm run dev
  download-test-data:
    desc: logs into real data sources and downloads data for later use
    dir: testdata
    cmds:
      - go test -tags=gentestdata .

