# https://taskfile.dev/installation/

version: '3'


vars:
  # small protection from deploying to wrong account
  EXPECTED_AWS_ACCOUNT_ID: "647278206015"


dotenv: ['.env']

tasks:
  lint:
    desc: various code and config checks
    cmds:
      - golangci-lint run --fix ./...
      - sam validate --lint
  deploy:
    desc: rebuilds everything and deploys lambda with AWS SAM
    cmds:
      - |
        echo "Checking AWS account..."
        CURRENT_AWS_ACCOUNT=$(aws sts get-caller-identity --query Account --output text)
        if [ "$CURRENT_AWS_ACCOUNT" != "{{.EXPECTED_AWS_ACCOUNT_ID}}" ]; then
          echo "Error: Incorrect AWS account. Expected {{.EXPECTED_AWS_ACCOUNT_ID}}, but got $CURRENT_AWS_ACCOUNT."
          exit 1
        fi
      - cd ui && npm run build
      - sam build
      - sam deploy
  apiserver:
    desc: runs API server. needs to be restarted after code changes.
    cmds:
      - sam local start-api
  uiserver:
    desc: runs UI server. has live reload; needs api server running in parallel
    dir: ui
    cmds:
      - npm run dev
