Transform: AWS::Serverless-2016-10-31
Resources:
  LambdaHandler:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      FunctionName: vjgdienynas-api
      Runtime: provided.al2023
      CodeUri: .
      Handler: bootstrap
      Architectures:
        - x86_64
      Timeout: 60
      Events:
        RootPath:
          Type: HttpApi
          Properties:
            Path: /
            Method: ANY
            ApiId: !Ref DefaultHttpAPI
        HttpApi:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: ANY
            ApiId: !Ref DefaultHttpAPI

  DefaultHttpAPI:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: '$default'

  CustomDomainName:
    Type: AWS::ApiGatewayV2::DomainName
    Properties:
      DomainName: "vjgdiary.neglostyti.com"
      DomainNameConfigurations:
        - CertificateArn: "arn:aws:acm:eu-central-1:647278206015:certificate/73186c7e-3eb1-4917-b073-50ef71522bb4"

  ApiMapping:
    Type: AWS::ApiGatewayV2::ApiMapping
    Properties:
      ApiId: !Ref DefaultHttpAPI
      DomainName: !Ref CustomDomainName
      Stage: '$default'

  LambdaHandlerLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${LambdaHandler}
      RetentionInDays: 1

